name: Deploy PR Previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose build
    - name: Build the website
      run: docker-compose run build
    - name: PR Preview Deploy
      uses: rossjrw/pr-preview-action@v1
      with:
        source-dir: ./.output/


#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
